server:
  port: 8072

spring:
  application:
    name: service-order
  datasource:
    name: db-order
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用 druid 作为连接池  更多配置的说明可以参见 druid starter 中文文档 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 10
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
      # Destroy 线程会检测连接的间隔时间，如果连接空闲时间大于等于 minEvictableIdleTimeMillis 则关闭物理连接。
      timeBetweenEvictionRunsMillis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      minEvictableIdleTimeMillis: 300000
      # 用来检测连接是否有效的 sql 因数据库方言而差, 例如 oracle 应该写成 SELECT 1 FROM DUAL
      validationQuery: SELECT 1
      # 建议配置为 true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，执行 validationQuery 检测连接是否有效。
      testWhileIdle: true
      # 申请连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnBorrow: false
      # 归还连接时执行 validationQuery 检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false
      # 是否自动回收超时连接
      removeAbandoned: true
      # 超时时间 (以秒数为单位)
      remove-abandoned-timeout: 180
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848  #nacos注册中心地址
    sentinel:
      transport:
        port: 8719 #(默认8719)跟控制台交流的端口，随意指定一个未被占用的端口即可
        dashboard: 127.0.0.1:2222 #指定控制台（dashboard）的服务的地址
        clientIp: 127.0.0.1 #指定客户端（微服务的）地址
#        heartbeatIntervalMs: 1000 #心跳检测间隔时间，默认10s,在simpleHttpHeartbeatSender
      datasource: #sentinel持久化配置规则到nacos
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848  #nacos注册中心地址
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  zipkin:
    base-url: http://127.0.0.1:9999
    discovery-client-enabled: false #让nacos把他当成url,而不是当作服务名
  sleuth:
    sampler:
      probability: 1.0 #采样百分比[0.1~1.0]，生产环境根据实际情况配置，配置的太大会影响服务的性能

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.shopmall.entity
  # Mybatis SQL语句控制台打印
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#rocketmq相关配置
rocketmq:
  name-server: 127.0.0.1:9876 #nameServer地址
  producer:
    group: shop-order  #生产组名
